server:
  #服务启动的端口号
  port: 8200
eureka:
  client:
    service-url:
      #eureka的注册地址
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8300
  cloud:
    gateway:
      routes:
        #gateway的服务名称
        - id: springcloud-oauth-service
          #gateway服务跳转地址，lb支持负载均衡
          uri: lb://springcloud-oauth
          #gateway跳转规则，只要已/oauth/开头的则进行跳转
          predicates:
            - Path=/oauth/**
          filters:
            #gateway地址过滤，去掉/oauth/地址
            - StripPrefix=1
            #gateway地址过滤，去掉/oauth/地址
            #- RewritePath=/oauth/(?<segment>.*), /$\{segment}
            - name: Retry
              args:
                #最初重试间隔为 1000 毫秒
                initial-interval: 1000
                #最多重试 6 次
                max-attempts: 6
                #最长重试间隔为 2000 毫秒
                max-interval: 2000
                #每次重试失败后，重试间隔所增加的倍数
                multiplier: 1.1
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always