server:
  #服务启动的端口号
  port: 8400
eureka:
  client:
    service-url:
      #eureka的服务注册地址
      defaultZone: http://127.0.0.1:8000/eureka
feign:
  hystrix:
    #开启熔断
    enabled: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  boot:
    admin:
      client:
        url: http://127.0.0.1:8300