server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: springcloud-gateway-service
          uri: https://blog.csdn.net
          predicates:
            - Path=/meteor_93/**