server:
  #服务启动的端口号
  port: 8200
eureka:
  client:
    service-url:
      #eureka的注册地址
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8300
  cloud:
    gateway:
      routes:
        #gateway的服务名称
        - id: springcloud-oauth-service
          #gateway服务跳转地址，lb支持负载均衡
          uri: lb://springcloud-oauth
          #gateway跳转规则，只要已/oauth/开头的则进行跳转
          predicates:
            - Path=/oauth/**
          filters:
            #gateway地址过滤，去掉/oauth/地址
            - StripPrefix=1
            #gateway地址过滤，去掉/oauth/地址
            #- RewritePath=/oauth/(?<segment>.*), /$\{segment}
            - name: Retry
              args:
                #用来指定哪些段的状态码需要重试，默认SERVER_ERROR，即5xx
                series:
                  - SERVER_ERROR
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                #重试次数
                retries: 6
                methods:
                  - GET
                exceptions:
                  - java.io.IOException
                  - java.util.concurrent.TimeoutException
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always