server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: springcloud-gateway-service
          uri: lb://springcloud-oauth
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/(?<segment>.*), /$\{segment}